name: Build and Deploy to Docker Swarm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build . -t indrarn/be-zero:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: docker push indrarn/be-zero:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: convert tag
      run: |
        IMAGE_TAG=${{ github.sha }}
        sed "s/\${IMAGE_TAG}/${IMAGE_TAG}/g" stacks/docker-compose.template.yaml > docker-compose.yaml

    - name: Deploy to Docker Swarm
      env:
        DOCKER_HOST: tcp://34.128.107.69:2377
      run: |
        docker stack deploy -c stacks/docker-compose.yaml be-zero

