name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build . -t indrarn/be-zero:${{ github.sha }}

    - name: Push Docker image
      run: docker push indrarn/be-zero:${{ github.sha }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Deploy stack to swarm
      uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: ssh://${{ secrets.SWARM_USER }}@${{ secrets.SWARM_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY}}
        args: stack deploy --compose-file docker-compose.yaml coolapp
