name: Build and Deploy to Docker Swarm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build . -t indrarn/be-zero:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: docker push indrarn/be-zero:${{ github.sha }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Copy SSH key and set permissions
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SWARM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Docker Swarm
      shell: sh
      env:
        DOCKER_HOST: "ssh://${{ secrets.SWARM_USER }}@${{ secrets.SWARM_HOST }}"
        DOCKER_TLS_VERIFY: "0"
      run: |
        echo "Deploying stack to Docker Swarm"
        docker --log-level debug stack deploy -c docker-compose.yml backend
