name: Build and Deploy to Docker Swarm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build . -t indrarn/be-zero:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: docker push indrarn/be-zero:${{ github.sha }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Deploy to Docker Swarm
      uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: ssh://root@34.128.107.69
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        args: stack deploy --compose-file docker-compose.yml backend
