name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build . -t indrarn/be-zero:${{ github.sha }}

    - name: Push Docker image
      run: docker push indrarn/be-zero:${{ github.sha }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GCP_REGION }}
        TF_VAR_zone: ${{ secrets.GCP_ZONE }}
        TF_VAR_credentials: ${{ secrets.GOOGLE_CREDENTIALS_PATH }}
        TF_VAR_name_instance: "docker-swarm"
        TF_VAR_spec: "e2-standard-4"
        TF_VAR_network_tags: "docker-swarm"
        TF_VAR_image: "ubuntu-os-cloud/ubuntu-2204-lts"
        TF_VAR_network: "default"
        TF_VAR_subnetwork: "default"

    - name: Get Public IP
      run: terraform output -raw instance_public_ip > terraform/public_ip.txt
      working-directory: ./terraform

    - name: Use Public IP
      run: |
        PUBLIC_IP=$(cat terraform/public_ip.txt)
        echo "Public IP is $PUBLIC_IP"
